### ISSUE TITLE
Deprecate this repo in favor of the new one

### ISSUE THREAD

**Issue by dandv** [reciprocity-archive/grc#1]
The new repo for GGRC is https://github.com/reciprocity/ggrc-core.

Whoever has access here could update the README and set the URL of this GitHub repo to https://github.com/reciprocity/ggrc-core

Example:

[![Set GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6424094/44108ff8-bea6-11e4-9830-b457b8488370.png)](https://github.com/dandv/meteor-webix)

**Comment by anze3db** [comment]
Updated the description, but not the README (I don't want to disturb the sleeping repository) :)
